In [1]:
temperature = 28


In [3]:
if temperature > 20:
    print('hot hot hot')

hot hot hot


In [5]:
temperature = 16

if temperature > 20:
    print("hot hot hot")
elif temperature < 10:
    print('okay, cold')
else:
    print('perfect')

perfect


In [6]:
numbers = [1,2,3,4]
for number in numbers:
    print(number * 2)

2
4
6
8


In [7]:
person = {
    "name":"Del",
    "age":63,
    "language":['English', 'Puns']
}

for value in person.values():
    print(value)


Del
63
['English', 'Puns']


In [16]:
numbers = [1, 6, 2, 2, 7, 1, 6, 13, 99, 7]

In [17]:
even_numbers = []

In [18]:
for n in numbers :
    if n % 2 == 0:
        even_numbers.append(n)
print(even_numbers)

[6, 2, 2, 6]


In [20]:
numbers = [1,2,3,4]
number_sq = []

In [21]:
for number in numbers:
    number_sq.append(number*number)
number_sq

[1, 4, 9, 16]

In [23]:
number_sq = [number* number for number in numbers]
number_sq

[1, 4, 9, 16]

In [24]:
multiples_of_12 = []

for number in range(101):
    if number % 12 == 0:
        multiples_of_12.append(number)
multiples_of_12

[0, 12, 24, 36, 48, 60, 72, 84, 96]

In [25]:
[number for number in range(101) if number % 12 == 0]

[0, 12, 24, 36, 48, 60, 72, 84, 96]

In [27]:
words = ["apple","orange", "lemon"]
length_of_word = {word: len(word) for word in words}
length_of_word

{'apple': 5, 'orange': 6, 'lemon': 5}

#first loop
primes = []
for i in range(2, 100):
    if i % 2 != 0 and i % 3 != 0 and i % 5 != 0 and i % 7 !=0 and i % 11 != 0:
        primes.append(i)

#second loop
ordinal_dict = {}

for number in range(4, 11):
    ordinal_dict[number] = str(number) + 'th'

In [30]:
[i for i in range(2, 100)  if i % 2 != 0 and i % 3 != 0 and i % 5 != 0 and i % 7 !=0 and i % 11 != 0 ]

[13,
 17,
 19,
 23,
 29,
 31,
 37,
 41,
 43,
 47,
 53,
 59,
 61,
 67,
 71,
 73,
 79,
 83,
 89,
 97]

#second loop
ordinal_dict = {}

for number in range(4, 11):
    ordinal_dict[number] = str(number) + 'th'

In [31]:
{i : str(i) + 'th' for i in range(4,11)}

{4: '4th', 5: '5th', 6: '6th', 7: '7th', 8: '8th', 9: '9th', 10: '10th'}

# functions

In [33]:
def greet():
    print("hey")

In [35]:
def greet():
    return "Hey!"

In [36]:
greet()

'Hey!'

In [40]:
def greet(name):
    return "Hey " + name

In [41]:
greet("Colin")

'Hey Colin'

In [42]:
def greet(name, time_of_day):
    return "Good " + time_of_day + ", " + name

In [43]:
greet("Colin", "Morning")

'Good Morning, Colin'

In [44]:
def mean(x,y):
    return (x + y)/2

In [45]:
mean(4,6)

5.0

In [46]:
def is_even(number):
	if(number % 2 == 0):
		return True
	else:
		return False

def sum_of_even_numbers(numbers):
	running_total = 0
	for number in numbers:
		if(is_even(number)):
			running_total += number
	return running_total

In [47]:
is_even(5)

False

In [48]:
sum_of_even_numbers([1,2,3,4])

6

In [52]:
def square(number):
    return number ** 2

def modfify(number, modiferier_function):
    return modiferier_function(number)



In [53]:
modfify(3, square)

9

In [54]:
def make_price(price):
    return "£" + str(price)
make_price(5)

'£5'

# Numpy

In [55]:
import numpy as np

In [57]:
my_array = np.array([1,2,3])

print(my_array)

[1 2 3]


In [58]:
my_2d_array = np.array([[1,2,3], [4,5,6]])
print(my_2d_array)

[[1 2 3]
 [4 5 6]]


In [59]:
my_array[0]

1

In [60]:
my_2d_array[1,1]

5

# Pandas

In [61]:
import pandas as pd